# Generated by Django 3.1.7 on 2021-04-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irdc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='word')),
            ],
            options={
                'verbose_name': 'IDF',
                'verbose_name_plural': 'IDFs',
            },
        ),
        migrations.CreateModel(
            name='TermFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.IntegerField(verbose_name='term frequency')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irdc.question', verbose_name='question')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irdc.idf', verbose_name='word')),
            ],
            options={
                'verbose_name': 'TermFrequency',
                'verbose_name_plural': 'TermFrequencies',
            },
        ),
    ]
