# Generated by Django 3.1.7 on 2021-04-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irdc', '0002_idf_termfrequency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='termfrequency',
            unique_together={('word', 'qid')},
        ),
    ]
