# Generated by Django 3.1.7 on 2021-04-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irdc', '0003_auto_20210401_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='idf',
            name='idf',
            field=models.FloatField(default=0, verbose_name='idf'),
        ),
    ]
